export const GET_LIST_ROOM = 'GET_LIST_ROOM';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const EDITING = 'EDITING';
export const CANCEL_EDITING = 'CANCEL_EDITING';
export const GET_LIST_ROOM_TYPE = 'GET_LIST_ROOM_TYPE';
export const UPDATE_INFORMATION_ROOM = 'UPDATE_INFORMATION_ROOM'
export const UPDATE_VISIBLE = 'UPDATE_VISIBLE'