export const GET_LIST_ROOM = 'GET_LIST_ROOM';
export const UPDATE_CHECK_IN_CUSTOMER = 'UPDATE_CHECK_IN_CUSTOMER';
export const UPDATE_CHECK_IN_ROOM = 'UPDATE_CHECK_IN_ROOM';
export const GET_LIST_CUSTOMER_TYPE = 'GET_LIST_CUSTOMER_TYPE';

export const STATUS = {
  AVAILABLE: 1,
  RENT: 2,
  RESERVED: 3,
  CLEANING: 4,
};
