export const FETCH_ROOM_TYPE = 'FETCH_ROOM_TYPE';
export const UPDATE_EDITING = 'UPDATE_EDITING';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const UPDATE_VISIBLE = 'UPDATE_VISIBLE_TYPE';
export const VISIBLE_FALSE = 'VISIBLE_FALSE'
export const CANCEL_EDIT ='CANCEL_EDIT_TYPE'